# Form implementation generated from reading ui file 'main_window_simple.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(402, 211)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 271, 161))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.push_button_ok = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_button_ok.setGeometry(QtCore.QRect(300, 20, 75, 24))
        self.push_button_ok.setObjectName("push_button_ok")
        self.push_button_cancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.push_button_cancel.setGeometry(QtCore.QRect(300, 50, 75, 24))
        self.push_button_cancel.setObjectName("push_button_cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 402, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_button_ok.setText(_translate("MainWindow", "OK"))
        self.push_button_cancel.setText(_translate("MainWindow", "Cancel"))

class InheritedMainWindow(Ui_MainWindow):
    def setupUi(self, MainWindow):
        super().setupUi(MainWindow)
        self.plainTextEdit.textChanged.connect(self.get_text_from_plaint_textbox)
        self.push_button_ok.clicked.connect(self.add_text_to_plaint_textbox)

    def add_text_to_plaint_textbox(self):
        self.plainTextEdit.setPlainText("Ok button was pushed")

    def get_text_from_plaint_textbox(self):
        print(self.plainTextEdit.toPlainText())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = InheritedMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
