"""renamed column name

Revision ID: 9aca290066d4
Revises: 31573dcfca31
Create Date: 2025-01-30 19:17:36.532748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aca290066d4'
down_revision = '31573dcfca31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_event', sa.String(length=80), nullable=False))
        #batch_op.create_unique_constraint(None, ['name_event'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name_event')

    # ### end Alembic commands ###
